/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IFanFuelBank, IFanFuelBankInterface } from "../../interfaces/IFanFuelBank.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "fan",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "fan",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "reason",
        "type": "bytes32"
      }
    ],
    "name": "reward",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "fan",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "reason",
        "type": "bytes32"
      }
    ],
    "name": "spendFrom",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IFanFuelBank__factory {
    static readonly abi = _abi;
    static createInterface(): IFanFuelBankInterface {
      return new Interface(_abi) as IFanFuelBankInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IFanFuelBank {
      return new Contract(address, _abi, runner) as unknown as IFanFuelBank;
    }
  }
  