/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IFanScoreRegistry, IFanScoreRegistryInterface } from "../../interfaces/IFanScoreRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "fan",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "artistKey",
        "type": "bytes32"
      }
    ],
    "name": "artistAttendanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "fan",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "artistKey",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "scoreAmount",
        "type": "uint256"
      }
    ],
    "name": "recordAttendance",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "fan",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "artistKey",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "scoreAmount",
        "type": "uint256"
      }
    ],
    "name": "recordBuyback",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "fan",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "artistKey",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "scoreAmount",
        "type": "uint256"
      }
    ],
    "name": "recordMint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "fan",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "artistKey",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "scoreAmount",
        "type": "uint256"
      }
    ],
    "name": "recordPurchase",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "fan",
        "type": "address"
      }
    ],
    "name": "reputationOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "fan",
        "type": "address"
      }
    ],
    "name": "tierOf",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IFanScoreRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IFanScoreRegistryInterface {
      return new Interface(_abi) as IFanScoreRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IFanScoreRegistry {
      return new Contract(address, _abi, runner) as unknown as IFanScoreRegistry;
    }
  }
  