/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IInsurancePool, IInsurancePoolInterface } from "../../interfaces/IInsurancePool.js";

  const _abi = [
  {
    "inputs": [],
    "name": "currentPolicy",
    "outputs": [
      {
        "internalType": "bool",
        "name": "active",
        "type": "bool"
      },
      {
        "internalType": "uint16",
        "name": "payoutBps",
        "type": "uint16"
      },
      {
        "internalType": "uint64",
        "name": "roundId",
        "type": "uint64"
      },
      {
        "internalType": "bytes32",
        "name": "reportHash",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "registerCoverage",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class IInsurancePool__factory {
    static readonly abi = _abi;
    static createInterface(): IInsurancePoolInterface {
      return new Interface(_abi) as IInsurancePoolInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IInsurancePool {
      return new Contract(address, _abi, runner) as unknown as IInsurancePool;
    }
  }
  