/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ChainTicketFactoryV2 {
      
    export type EventDeploymentStruct = {eventId: string, name: string, symbol: string, artistId: string, seriesId: string, primaryPrice: BigNumberish, maxSupply: BigNumberish, fanPassAllocationBps: BigNumberish, artistRoyaltyBps: BigNumberish, treasury: AddressLike, admin: AddressLike, ticketNFT: AddressLike, marketplace: AddressLike, checkInRegistry: AddressLike, collectibleContract: AddressLike, fanScoreRegistry: AddressLike, fanFuelBank: AddressLike, insurancePool: AddressLike, oracleAdapter: AddressLike, merchStore: AddressLike, perkManager: AddressLike, deploymentBlock: BigNumberish, registeredAt: BigNumberish}

    export type EventDeploymentStructOutput = [eventId: string, name: string, symbol: string, artistId: string, seriesId: string, primaryPrice: bigint, maxSupply: bigint, fanPassAllocationBps: bigint, artistRoyaltyBps: bigint, treasury: string, admin: string, ticketNFT: string, marketplace: string, checkInRegistry: string, collectibleContract: string, fanScoreRegistry: string, fanFuelBank: string, insurancePool: string, oracleAdapter: string, merchStore: string, perkManager: string, deploymentBlock: bigint, registeredAt: bigint] & {eventId: string, name: string, symbol: string, artistId: string, seriesId: string, primaryPrice: bigint, maxSupply: bigint, fanPassAllocationBps: bigint, artistRoyaltyBps: bigint, treasury: string, admin: string, ticketNFT: string, marketplace: string, checkInRegistry: string, collectibleContract: string, fanScoreRegistry: string, fanFuelBank: string, insurancePool: string, oracleAdapter: string, merchStore: string, perkManager: string, deploymentBlock: bigint, registeredAt: bigint }
  

    export type RegisterEventParamsStruct = {eventId: string, name: string, symbol: string, artistId: string, seriesId: string, primaryPrice: BigNumberish, maxSupply: BigNumberish, fanPassAllocationBps: BigNumberish, artistRoyaltyBps: BigNumberish, treasury: AddressLike, admin: AddressLike, ticketNFT: AddressLike, marketplace: AddressLike, checkInRegistry: AddressLike, collectibleContract: AddressLike, fanScoreRegistry: AddressLike, fanFuelBank: AddressLike, insurancePool: AddressLike, oracleAdapter: AddressLike, merchStore: AddressLike, perkManager: AddressLike, deploymentBlock: BigNumberish}

    export type RegisterEventParamsStructOutput = [eventId: string, name: string, symbol: string, artistId: string, seriesId: string, primaryPrice: bigint, maxSupply: bigint, fanPassAllocationBps: bigint, artistRoyaltyBps: bigint, treasury: string, admin: string, ticketNFT: string, marketplace: string, checkInRegistry: string, collectibleContract: string, fanScoreRegistry: string, fanFuelBank: string, insurancePool: string, oracleAdapter: string, merchStore: string, perkManager: string, deploymentBlock: bigint] & {eventId: string, name: string, symbol: string, artistId: string, seriesId: string, primaryPrice: bigint, maxSupply: bigint, fanPassAllocationBps: bigint, artistRoyaltyBps: bigint, treasury: string, admin: string, ticketNFT: string, marketplace: string, checkInRegistry: string, collectibleContract: string, fanScoreRegistry: string, fanFuelBank: string, insurancePool: string, oracleAdapter: string, merchStore: string, perkManager: string, deploymentBlock: bigint }
  
    }

  export interface ChainTicketFactoryV2Interface extends Interface {
    getFunction(nameOrSignature: "CREATOR_ROLE" | "DEFAULT_ADMIN_ROLE" | "getEventAt" | "getEventById" | "getRoleAdmin" | "grantRole" | "hasRole" | "registerEvent" | "renounceRole" | "revokeRole" | "supportsInterface" | "totalEvents"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EventRegistered" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'CREATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'getEventAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEventById', values: [string]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'registerEvent', values: [ChainTicketFactoryV2.RegisterEventParamsStruct]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalEvents', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'CREATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEventAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEventById', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEvents', data: BytesLike): Result;
  }

  
    export namespace EventRegisteredEvent {
      export type InputTuple = [eventKey: BytesLike, eventId: string, artistId: string, admin: AddressLike, ticketNFT: AddressLike, marketplace: AddressLike, checkInRegistry: AddressLike];
      export type OutputTuple = [eventKey: string, eventId: string, artistId: string, admin: string, ticketNFT: string, marketplace: string, checkInRegistry: string];
      export interface OutputObject {eventKey: string, eventId: string, artistId: string, admin: string, ticketNFT: string, marketplace: string, checkInRegistry: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ChainTicketFactoryV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): ChainTicketFactoryV2;
    waitForDeployment(): Promise<this>;

    interface: ChainTicketFactoryV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CREATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getEventAt: TypedContractMethod<
      [index: BigNumberish, ],
      [ChainTicketFactoryV2.EventDeploymentStructOutput],
      'view'
    >
    

    
    getEventById: TypedContractMethod<
      [eventId: string, ],
      [ChainTicketFactoryV2.EventDeploymentStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    registerEvent: TypedContractMethod<
      [params: ChainTicketFactoryV2.RegisterEventParamsStruct, ],
      [ChainTicketFactoryV2.EventDeploymentStructOutput],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalEvents: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CREATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getEventAt'): TypedContractMethod<
      [index: BigNumberish, ],
      [ChainTicketFactoryV2.EventDeploymentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getEventById'): TypedContractMethod<
      [eventId: string, ],
      [ChainTicketFactoryV2.EventDeploymentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerEvent'): TypedContractMethod<
      [params: ChainTicketFactoryV2.RegisterEventParamsStruct, ],
      [ChainTicketFactoryV2.EventDeploymentStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalEvents'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'EventRegistered'): TypedContractEvent<EventRegisteredEvent.InputTuple, EventRegisteredEvent.OutputTuple, EventRegisteredEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'EventRegistered(bytes32,string,string,address,address,address,address)': TypedContractEvent<EventRegisteredEvent.InputTuple, EventRegisteredEvent.OutputTuple, EventRegisteredEvent.OutputObject>;
      EventRegistered: TypedContractEvent<EventRegisteredEvent.InputTuple, EventRegisteredEvent.OutputTuple, EventRegisteredEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }