/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FanScoreRegistryInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "GOLD_THRESHOLD" | "PLATINUM_THRESHOLD" | "SILVER_THRESHOLD" | "SOURCE_ROLE" | "artistAttendanceOf" | "getRoleAdmin" | "grantRole" | "hasRole" | "recordAttendance" | "recordBuyback" | "recordMint" | "recordPurchase" | "renounceRole" | "reputationOf" | "revokeRole" | "supportsInterface" | "tierOf"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ArtistAttendanceRecorded" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "ScoreAwarded"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'GOLD_THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'PLATINUM_THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'SILVER_THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'SOURCE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'artistAttendanceOf', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'recordAttendance', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordBuyback', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordMint', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordPurchase', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'reputationOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'tierOf', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GOLD_THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PLATINUM_THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SILVER_THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SOURCE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'artistAttendanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordAttendance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordBuyback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordPurchase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tierOf', data: BytesLike): Result;
  }

  
    export namespace ArtistAttendanceRecordedEvent {
      export type InputTuple = [fan: AddressLike, artistKey: BytesLike, newAttendanceCount: BigNumberish];
      export type OutputTuple = [fan: string, artistKey: string, newAttendanceCount: bigint];
      export interface OutputObject {fan: string, artistKey: string, newAttendanceCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ScoreAwardedEvent {
      export type InputTuple = [fan: AddressLike, artistKey: BytesLike, amount: BigNumberish, reason: BytesLike, newScore: BigNumberish];
      export type OutputTuple = [fan: string, artistKey: string, amount: bigint, reason: string, newScore: bigint];
      export interface OutputObject {fan: string, artistKey: string, amount: bigint, reason: string, newScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FanScoreRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): FanScoreRegistry;
    waitForDeployment(): Promise<this>;

    interface: FanScoreRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    GOLD_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PLATINUM_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SILVER_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SOURCE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    artistAttendanceOf: TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    recordAttendance: TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordBuyback: TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordMint: TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordPurchase: TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    reputationOf: TypedContractMethod<
      [fan: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    tierOf: TypedContractMethod<
      [fan: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'GOLD_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PLATINUM_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SILVER_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SOURCE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'artistAttendanceOf'): TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordAttendance'): TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordBuyback'): TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordMint'): TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordPurchase'): TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationOf'): TypedContractMethod<
      [fan: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'tierOf'): TypedContractMethod<
      [fan: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'ArtistAttendanceRecorded'): TypedContractEvent<ArtistAttendanceRecordedEvent.InputTuple, ArtistAttendanceRecordedEvent.OutputTuple, ArtistAttendanceRecordedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'ScoreAwarded'): TypedContractEvent<ScoreAwardedEvent.InputTuple, ScoreAwardedEvent.OutputTuple, ScoreAwardedEvent.OutputObject>;

    filters: {
      
      'ArtistAttendanceRecorded(address,bytes32,uint256)': TypedContractEvent<ArtistAttendanceRecordedEvent.InputTuple, ArtistAttendanceRecordedEvent.OutputTuple, ArtistAttendanceRecordedEvent.OutputObject>;
      ArtistAttendanceRecorded: TypedContractEvent<ArtistAttendanceRecordedEvent.InputTuple, ArtistAttendanceRecordedEvent.OutputTuple, ArtistAttendanceRecordedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'ScoreAwarded(address,bytes32,uint256,bytes32,uint256)': TypedContractEvent<ScoreAwardedEvent.InputTuple, ScoreAwardedEvent.OutputTuple, ScoreAwardedEvent.OutputObject>;
      ScoreAwarded: TypedContractEvent<ScoreAwardedEvent.InputTuple, ScoreAwardedEvent.OutputTuple, ScoreAwardedEvent.OutputObject>;
    
    };
  }