/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace MarketplaceV2 {
      
    export type ListingStruct = {seller: AddressLike, price: BigNumberish}

    export type ListingStructOutput = [seller: string, price: bigint] & {seller: string, price: bigint }
  
    }

  export interface MarketplaceV2Interface extends Interface {
    getFunction(nameOrSignature: "BUYBACK_FUEL_REWARD" | "BUYBACK_ROLE" | "BUYBACK_SCORE_REWARD" | "DEFAULT_ADMIN_ROLE" | "SECONDARY_PURCHASE_FUEL_REWARD" | "SECONDARY_PURCHASE_SCORE_REWARD" | "artistKey" | "artistRoyaltyBps" | "buy" | "cancel" | "fanFuelBank" | "fanScoreRegistry" | "getListing" | "getRoleAdmin" | "grantRole" | "hasRole" | "list" | "listWithPermit" | "organizerBuyback" | "renounceRole" | "revokeRole" | "supportsInterface" | "ticketNFT" | "treasury"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Buyback" | "Cancelled" | "Listed" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Sold"): EventFragment;

    encodeFunctionData(functionFragment: 'BUYBACK_FUEL_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'BUYBACK_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'BUYBACK_SCORE_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'SECONDARY_PURCHASE_FUEL_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'SECONDARY_PURCHASE_SCORE_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'artistKey', values?: undefined): string;
encodeFunctionData(functionFragment: 'artistRoyaltyBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'buy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fanFuelBank', values?: undefined): string;
encodeFunctionData(functionFragment: 'fanScoreRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'getListing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'list', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'listWithPermit', values: [BigNumberish, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'organizerBuyback', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'ticketNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BUYBACK_FUEL_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BUYBACK_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BUYBACK_SCORE_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SECONDARY_PURCHASE_FUEL_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SECONDARY_PURCHASE_SCORE_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'artistKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'artistRoyaltyBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fanFuelBank', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fanScoreRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'list', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listWithPermit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'organizerBuyback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ticketNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
  }

  
    export namespace BuybackEvent {
      export type InputTuple = [tokenId: BigNumberish, seller: AddressLike, organizer: AddressLike, price: BigNumberish];
      export type OutputTuple = [tokenId: bigint, seller: string, organizer: string, price: bigint];
      export interface OutputObject {tokenId: bigint, seller: string, organizer: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CancelledEvent {
      export type InputTuple = [tokenId: BigNumberish, actor: AddressLike];
      export type OutputTuple = [tokenId: bigint, actor: string];
      export interface OutputObject {tokenId: bigint, actor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListedEvent {
      export type InputTuple = [tokenId: BigNumberish, seller: AddressLike, price: BigNumberish];
      export type OutputTuple = [tokenId: bigint, seller: string, price: bigint];
      export interface OutputObject {tokenId: bigint, seller: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SoldEvent {
      export type InputTuple = [tokenId: BigNumberish, seller: AddressLike, buyer: AddressLike, price: BigNumberish, artistRoyaltyAmount: BigNumberish];
      export type OutputTuple = [tokenId: bigint, seller: string, buyer: string, price: bigint, artistRoyaltyAmount: bigint];
      export interface OutputObject {tokenId: bigint, seller: string, buyer: string, price: bigint, artistRoyaltyAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MarketplaceV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): MarketplaceV2;
    waitForDeployment(): Promise<this>;

    interface: MarketplaceV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BUYBACK_FUEL_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BUYBACK_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    BUYBACK_SCORE_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    SECONDARY_PURCHASE_FUEL_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SECONDARY_PURCHASE_SCORE_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    artistKey: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    artistRoyaltyBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buy: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    cancel: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fanFuelBank: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fanScoreRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getListing: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [MarketplaceV2.ListingStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    list: TypedContractMethod<
      [tokenId: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    listWithPermit: TypedContractMethod<
      [tokenId: BigNumberish, price: BigNumberish, deadline: BigNumberish, signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    organizerBuyback: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    ticketNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BUYBACK_FUEL_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BUYBACK_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'BUYBACK_SCORE_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'SECONDARY_PURCHASE_FUEL_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SECONDARY_PURCHASE_SCORE_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'artistKey'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'artistRoyaltyBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancel'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fanFuelBank'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fanScoreRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getListing'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [MarketplaceV2.ListingStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'list'): TypedContractMethod<
      [tokenId: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listWithPermit'): TypedContractMethod<
      [tokenId: BigNumberish, price: BigNumberish, deadline: BigNumberish, signature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'organizerBuyback'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'ticketNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Buyback'): TypedContractEvent<BuybackEvent.InputTuple, BuybackEvent.OutputTuple, BuybackEvent.OutputObject>;
getEvent(key: 'Cancelled'): TypedContractEvent<CancelledEvent.InputTuple, CancelledEvent.OutputTuple, CancelledEvent.OutputObject>;
getEvent(key: 'Listed'): TypedContractEvent<ListedEvent.InputTuple, ListedEvent.OutputTuple, ListedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Sold'): TypedContractEvent<SoldEvent.InputTuple, SoldEvent.OutputTuple, SoldEvent.OutputObject>;

    filters: {
      
      'Buyback(uint256,address,address,uint256)': TypedContractEvent<BuybackEvent.InputTuple, BuybackEvent.OutputTuple, BuybackEvent.OutputObject>;
      Buyback: TypedContractEvent<BuybackEvent.InputTuple, BuybackEvent.OutputTuple, BuybackEvent.OutputObject>;
    

      'Cancelled(uint256,address)': TypedContractEvent<CancelledEvent.InputTuple, CancelledEvent.OutputTuple, CancelledEvent.OutputObject>;
      Cancelled: TypedContractEvent<CancelledEvent.InputTuple, CancelledEvent.OutputTuple, CancelledEvent.OutputObject>;
    

      'Listed(uint256,address,uint256)': TypedContractEvent<ListedEvent.InputTuple, ListedEvent.OutputTuple, ListedEvent.OutputObject>;
      Listed: TypedContractEvent<ListedEvent.InputTuple, ListedEvent.OutputTuple, ListedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Sold(uint256,address,address,uint256,uint256)': TypedContractEvent<SoldEvent.InputTuple, SoldEvent.OutputTuple, SoldEvent.OutputObject>;
      Sold: TypedContractEvent<SoldEvent.InputTuple, SoldEvent.OutputTuple, SoldEvent.OutputObject>;
    
    };
  }