/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TicketNFTV2Interface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "DOMAIN_SEPARATOR" | "FAN_PASS_ATTESTATION_TYPEHASH" | "FAN_PASS_MINT_FUEL_REWARD" | "FAN_PASS_MINT_SCORE_REWARD" | "PAUSER_ROLE" | "PERMIT_TYPEHASH" | "STANDARD_MINT_FUEL_REWARD" | "STANDARD_MINT_SCORE_REWARD" | "approve" | "artistId" | "artistKey" | "artistRoyaltyBps" | "attestationSigner" | "balanceOf" | "baseUris" | "checkInRegistry" | "collectibleMode" | "consumeForCheckIn" | "coverageClaimed" | "coverageOf" | "eip712Domain" | "fanFuelBank" | "fanPassAllocationBps" | "fanPassMinted" | "fanPassSupplyCap" | "fanScoreRegistry" | "getApproved" | "getRoleAdmin" | "grantRole" | "hasRole" | "insurancePool" | "insurancePremium" | "isApprovedForAll" | "isUsed" | "markCoverageClaimed" | "marketplace" | "maxPerWallet" | "maxSupply" | "mintFanPass" | "mintPrimary" | "mintStandard" | "name" | "nonces" | "ownerOf" | "pause" | "paused" | "permit" | "primaryPrice" | "renounceRole" | "revokeRole" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "seriesId" | "setApprovalForAll" | "setAttestationSigner" | "setBaseUri" | "setBaseUris" | "setCheckInRegistry" | "setCollectibleMode" | "setInsurancePool" | "setMarketplace" | "setRewardContracts" | "standardSupplyCap" | "supportsInterface" | "symbol" | "ticketClassOf" | "tokenURI" | "totalMinted" | "transferFrom" | "treasury" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalForAll" | "AttestationSignerUpdated" | "BaseUriUpdated" | "BaseUrisUpdated" | "BatchMetadataUpdate" | "CheckInRegistryUpdated" | "CollectibleModeUpdated" | "CoverageClaimMarked" | "CoveragePurchased" | "EIP712DomainChanged" | "FanPassMinted" | "InsurancePoolUpdated" | "MarketplaceUpdated" | "MetadataUpdate" | "Paused" | "PrimaryMinted" | "RewardsUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "StandardMinted" | "TicketConsumed" | "Transfer" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DOMAIN_SEPARATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'FAN_PASS_ATTESTATION_TYPEHASH', values?: undefined): string;
encodeFunctionData(functionFragment: 'FAN_PASS_MINT_FUEL_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'FAN_PASS_MINT_SCORE_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PERMIT_TYPEHASH', values?: undefined): string;
encodeFunctionData(functionFragment: 'STANDARD_MINT_FUEL_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'STANDARD_MINT_SCORE_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'artistId', values?: undefined): string;
encodeFunctionData(functionFragment: 'artistKey', values?: undefined): string;
encodeFunctionData(functionFragment: 'artistRoyaltyBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'attestationSigner', values?: undefined): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'baseUris', values?: undefined): string;
encodeFunctionData(functionFragment: 'checkInRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'collectibleMode', values?: undefined): string;
encodeFunctionData(functionFragment: 'consumeForCheckIn', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'coverageClaimed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'coverageOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string;
encodeFunctionData(functionFragment: 'fanFuelBank', values?: undefined): string;
encodeFunctionData(functionFragment: 'fanPassAllocationBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'fanPassMinted', values?: undefined): string;
encodeFunctionData(functionFragment: 'fanPassSupplyCap', values?: undefined): string;
encodeFunctionData(functionFragment: 'fanScoreRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'insurancePool', values?: undefined): string;
encodeFunctionData(functionFragment: 'insurancePremium', values?: undefined): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isUsed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markCoverageClaimed', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketplace', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxPerWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintFanPass', values: [BytesLike, boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintPrimary', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintStandard', values: [boolean]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'nonces', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'permit', values: [AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'primaryPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'seriesId', values?: undefined): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setAttestationSigner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setBaseUri', values: [string]): string;
encodeFunctionData(functionFragment: 'setBaseUris', values: [string, string]): string;
encodeFunctionData(functionFragment: 'setCheckInRegistry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setCollectibleMode', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setInsurancePool', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setMarketplace', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setRewardContracts', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'standardSupplyCap', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'ticketClassOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalMinted', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DOMAIN_SEPARATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FAN_PASS_ATTESTATION_TYPEHASH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FAN_PASS_MINT_FUEL_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FAN_PASS_MINT_SCORE_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PERMIT_TYPEHASH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STANDARD_MINT_FUEL_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STANDARD_MINT_SCORE_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'artistId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'artistKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'artistRoyaltyBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attestationSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baseUris', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkInRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collectibleMode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'consumeForCheckIn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'coverageClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'coverageOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fanFuelBank', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fanPassAllocationBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fanPassMinted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fanPassSupplyCap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fanScoreRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'insurancePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'insurancePremium', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markCoverageClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketplace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxPerWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintFanPass', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintPrimary', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintStandard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'permit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'primaryPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seriesId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAttestationSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBaseUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBaseUris', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCheckInRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCollectibleMode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setInsurancePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMarketplace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRewardContracts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'standardSupplyCap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ticketClassOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalMinted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AttestationSignerUpdatedEvent {
      export type InputTuple = [previousSigner: AddressLike, newSigner: AddressLike];
      export type OutputTuple = [previousSigner: string, newSigner: string];
      export interface OutputObject {previousSigner: string, newSigner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BaseUriUpdatedEvent {
      export type InputTuple = [baseTokenURI: string];
      export type OutputTuple = [baseTokenURI: string];
      export interface OutputObject {baseTokenURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BaseUrisUpdatedEvent {
      export type InputTuple = [baseTokenURI: string, collectibleBaseURI: string];
      export type OutputTuple = [baseTokenURI: string, collectibleBaseURI: string];
      export interface OutputObject {baseTokenURI: string, collectibleBaseURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchMetadataUpdateEvent {
      export type InputTuple = [_fromTokenId: BigNumberish, _toTokenId: BigNumberish];
      export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
      export interface OutputObject {_fromTokenId: bigint, _toTokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CheckInRegistryUpdatedEvent {
      export type InputTuple = [previousRegistry: AddressLike, newRegistry: AddressLike];
      export type OutputTuple = [previousRegistry: string, newRegistry: string];
      export interface OutputObject {previousRegistry: string, newRegistry: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CollectibleModeUpdatedEvent {
      export type InputTuple = [enabled: boolean];
      export type OutputTuple = [enabled: boolean];
      export interface OutputObject {enabled: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CoverageClaimMarkedEvent {
      export type InputTuple = [tokenId: BigNumberish, roundId: BigNumberish];
      export type OutputTuple = [tokenId: bigint, roundId: bigint];
      export interface OutputObject {tokenId: bigint, roundId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CoveragePurchasedEvent {
      export type InputTuple = [tokenId: BigNumberish, premiumPaid: BigNumberish];
      export type OutputTuple = [tokenId: bigint, premiumPaid: bigint];
      export interface OutputObject {tokenId: bigint, premiumPaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EIP712DomainChangedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FanPassMintedEvent {
      export type InputTuple = [buyer: AddressLike, tokenId: BigNumberish, insured: boolean];
      export type OutputTuple = [buyer: string, tokenId: bigint, insured: boolean];
      export interface OutputObject {buyer: string, tokenId: bigint, insured: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InsurancePoolUpdatedEvent {
      export type InputTuple = [previousPool: AddressLike, newPool: AddressLike];
      export type OutputTuple = [previousPool: string, newPool: string];
      export interface OutputObject {previousPool: string, newPool: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketplaceUpdatedEvent {
      export type InputTuple = [previousMarketplace: AddressLike, newMarketplace: AddressLike];
      export type OutputTuple = [previousMarketplace: string, newMarketplace: string];
      export interface OutputObject {previousMarketplace: string, newMarketplace: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MetadataUpdateEvent {
      export type InputTuple = [_tokenId: BigNumberish];
      export type OutputTuple = [_tokenId: bigint];
      export interface OutputObject {_tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PrimaryMintedEvent {
      export type InputTuple = [buyer: AddressLike, tokenId: BigNumberish, paidAmount: BigNumberish];
      export type OutputTuple = [buyer: string, tokenId: bigint, paidAmount: bigint];
      export interface OutputObject {buyer: string, tokenId: bigint, paidAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardsUpdatedEvent {
      export type InputTuple = [fanScoreRegistry: AddressLike, fanFuelBank: AddressLike];
      export type OutputTuple = [fanScoreRegistry: string, fanFuelBank: string];
      export interface OutputObject {fanScoreRegistry: string, fanFuelBank: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StandardMintedEvent {
      export type InputTuple = [buyer: AddressLike, tokenId: BigNumberish, insured: boolean];
      export type OutputTuple = [buyer: string, tokenId: bigint, insured: boolean];
      export interface OutputObject {buyer: string, tokenId: bigint, insured: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketConsumedEvent {
      export type InputTuple = [tokenId: BigNumberish, owner: AddressLike, ticketClass: BigNumberish];
      export type OutputTuple = [tokenId: bigint, owner: string, ticketClass: bigint];
      export interface OutputObject {tokenId: bigint, owner: string, ticketClass: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TicketNFTV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): TicketNFTV2;
    waitForDeployment(): Promise<this>;

    interface: TicketNFTV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DOMAIN_SEPARATOR: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    FAN_PASS_ATTESTATION_TYPEHASH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    FAN_PASS_MINT_FUEL_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FAN_PASS_MINT_SCORE_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PAUSER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PERMIT_TYPEHASH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    STANDARD_MINT_FUEL_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    STANDARD_MINT_SCORE_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    artistId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    artistKey: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    artistRoyaltyBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    attestationSigner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    baseUris: TypedContractMethod<
      [],
      [[string, string] & {baseTokenURI: string, collectibleBaseURI: string }],
      'view'
    >
    

    
    checkInRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    collectibleMode: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    consumeForCheckIn: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[string, bigint] & {owner: string, ticketClass: bigint }],
      'nonpayable'
    >
    

    
    coverageClaimed: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    coverageOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[boolean, boolean, boolean, bigint, bigint, bigint, bigint] & {insured: boolean, claimed: boolean, claimable: boolean, payoutBps: bigint, weatherRoundId: bigint, premiumPaid: bigint, payoutAmount: bigint }],
      'view'
    >
    

    
    eip712Domain: TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >
    

    
    fanFuelBank: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fanPassAllocationBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fanPassMinted: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fanPassSupplyCap: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fanScoreRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    insurancePool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    insurancePremium: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isUsed: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    markCoverageClaimed: TypedContractMethod<
      [tokenId: BigNumberish, roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    marketplace: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    maxPerWallet: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mintFanPass: TypedContractMethod<
      [attestation: BytesLike, insured: boolean, deadline: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    mintPrimary: TypedContractMethod<
      [],
      [bigint],
      'payable'
    >
    

    
    mintStandard: TypedContractMethod<
      [insured: boolean, ],
      [bigint],
      'payable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nonces: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    permit: TypedContractMethod<
      [spender: AddressLike, tokenId: BigNumberish, deadline: BigNumberish, signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    primaryPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    seriesId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setAttestationSigner: TypedContractMethod<
      [newAttestationSigner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setBaseUri: TypedContractMethod<
      [baseTokenURI_: string, ],
      [void],
      'nonpayable'
    >
    

    
    setBaseUris: TypedContractMethod<
      [baseTokenURI_: string, collectibleBaseURI_: string, ],
      [void],
      'nonpayable'
    >
    

    
    setCheckInRegistry: TypedContractMethod<
      [newRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setCollectibleMode: TypedContractMethod<
      [enabled: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setInsurancePool: TypedContractMethod<
      [newInsurancePool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMarketplace: TypedContractMethod<
      [newMarketplace: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRewardContracts: TypedContractMethod<
      [newFanScoreRegistry: AddressLike, newFanFuelBank: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    standardSupplyCap: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ticketClassOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalMinted: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DOMAIN_SEPARATOR'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'FAN_PASS_ATTESTATION_TYPEHASH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'FAN_PASS_MINT_FUEL_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FAN_PASS_MINT_SCORE_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PERMIT_TYPEHASH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'STANDARD_MINT_FUEL_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'STANDARD_MINT_SCORE_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'artistId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'artistKey'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'artistRoyaltyBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'attestationSigner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'baseUris'): TypedContractMethod<
      [],
      [[string, string] & {baseTokenURI: string, collectibleBaseURI: string }],
      'view'
    >;
getFunction(nameOrSignature: 'checkInRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'collectibleMode'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'consumeForCheckIn'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[string, bigint] & {owner: string, ticketClass: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'coverageClaimed'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'coverageOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[boolean, boolean, boolean, bigint, bigint, bigint, bigint] & {insured: boolean, claimed: boolean, claimable: boolean, payoutBps: bigint, weatherRoundId: bigint, premiumPaid: bigint, payoutAmount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'fanFuelBank'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fanPassAllocationBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fanPassMinted'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fanPassSupplyCap'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fanScoreRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'insurancePool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'insurancePremium'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isUsed'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'markCoverageClaimed'): TypedContractMethod<
      [tokenId: BigNumberish, roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'marketplace'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'maxPerWallet'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintFanPass'): TypedContractMethod<
      [attestation: BytesLike, insured: boolean, deadline: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'mintPrimary'): TypedContractMethod<
      [],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'mintStandard'): TypedContractMethod<
      [insured: boolean, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nonces'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'permit'): TypedContractMethod<
      [spender: AddressLike, tokenId: BigNumberish, deadline: BigNumberish, signature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'primaryPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'seriesId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAttestationSigner'): TypedContractMethod<
      [newAttestationSigner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBaseUri'): TypedContractMethod<
      [baseTokenURI_: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBaseUris'): TypedContractMethod<
      [baseTokenURI_: string, collectibleBaseURI_: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCheckInRegistry'): TypedContractMethod<
      [newRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCollectibleMode'): TypedContractMethod<
      [enabled: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setInsurancePool'): TypedContractMethod<
      [newInsurancePool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMarketplace'): TypedContractMethod<
      [newMarketplace: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRewardContracts'): TypedContractMethod<
      [newFanScoreRegistry: AddressLike, newFanFuelBank: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'standardSupplyCap'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ticketClassOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalMinted'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'AttestationSignerUpdated'): TypedContractEvent<AttestationSignerUpdatedEvent.InputTuple, AttestationSignerUpdatedEvent.OutputTuple, AttestationSignerUpdatedEvent.OutputObject>;
getEvent(key: 'BaseUriUpdated'): TypedContractEvent<BaseUriUpdatedEvent.InputTuple, BaseUriUpdatedEvent.OutputTuple, BaseUriUpdatedEvent.OutputObject>;
getEvent(key: 'BaseUrisUpdated'): TypedContractEvent<BaseUrisUpdatedEvent.InputTuple, BaseUrisUpdatedEvent.OutputTuple, BaseUrisUpdatedEvent.OutputObject>;
getEvent(key: 'BatchMetadataUpdate'): TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
getEvent(key: 'CheckInRegistryUpdated'): TypedContractEvent<CheckInRegistryUpdatedEvent.InputTuple, CheckInRegistryUpdatedEvent.OutputTuple, CheckInRegistryUpdatedEvent.OutputObject>;
getEvent(key: 'CollectibleModeUpdated'): TypedContractEvent<CollectibleModeUpdatedEvent.InputTuple, CollectibleModeUpdatedEvent.OutputTuple, CollectibleModeUpdatedEvent.OutputObject>;
getEvent(key: 'CoverageClaimMarked'): TypedContractEvent<CoverageClaimMarkedEvent.InputTuple, CoverageClaimMarkedEvent.OutputTuple, CoverageClaimMarkedEvent.OutputObject>;
getEvent(key: 'CoveragePurchased'): TypedContractEvent<CoveragePurchasedEvent.InputTuple, CoveragePurchasedEvent.OutputTuple, CoveragePurchasedEvent.OutputObject>;
getEvent(key: 'EIP712DomainChanged'): TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
getEvent(key: 'FanPassMinted'): TypedContractEvent<FanPassMintedEvent.InputTuple, FanPassMintedEvent.OutputTuple, FanPassMintedEvent.OutputObject>;
getEvent(key: 'InsurancePoolUpdated'): TypedContractEvent<InsurancePoolUpdatedEvent.InputTuple, InsurancePoolUpdatedEvent.OutputTuple, InsurancePoolUpdatedEvent.OutputObject>;
getEvent(key: 'MarketplaceUpdated'): TypedContractEvent<MarketplaceUpdatedEvent.InputTuple, MarketplaceUpdatedEvent.OutputTuple, MarketplaceUpdatedEvent.OutputObject>;
getEvent(key: 'MetadataUpdate'): TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PrimaryMinted'): TypedContractEvent<PrimaryMintedEvent.InputTuple, PrimaryMintedEvent.OutputTuple, PrimaryMintedEvent.OutputObject>;
getEvent(key: 'RewardsUpdated'): TypedContractEvent<RewardsUpdatedEvent.InputTuple, RewardsUpdatedEvent.OutputTuple, RewardsUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'StandardMinted'): TypedContractEvent<StandardMintedEvent.InputTuple, StandardMintedEvent.OutputTuple, StandardMintedEvent.OutputObject>;
getEvent(key: 'TicketConsumed'): TypedContractEvent<TicketConsumedEvent.InputTuple, TicketConsumedEvent.OutputTuple, TicketConsumedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'AttestationSignerUpdated(address,address)': TypedContractEvent<AttestationSignerUpdatedEvent.InputTuple, AttestationSignerUpdatedEvent.OutputTuple, AttestationSignerUpdatedEvent.OutputObject>;
      AttestationSignerUpdated: TypedContractEvent<AttestationSignerUpdatedEvent.InputTuple, AttestationSignerUpdatedEvent.OutputTuple, AttestationSignerUpdatedEvent.OutputObject>;
    

      'BaseUriUpdated(string)': TypedContractEvent<BaseUriUpdatedEvent.InputTuple, BaseUriUpdatedEvent.OutputTuple, BaseUriUpdatedEvent.OutputObject>;
      BaseUriUpdated: TypedContractEvent<BaseUriUpdatedEvent.InputTuple, BaseUriUpdatedEvent.OutputTuple, BaseUriUpdatedEvent.OutputObject>;
    

      'BaseUrisUpdated(string,string)': TypedContractEvent<BaseUrisUpdatedEvent.InputTuple, BaseUrisUpdatedEvent.OutputTuple, BaseUrisUpdatedEvent.OutputObject>;
      BaseUrisUpdated: TypedContractEvent<BaseUrisUpdatedEvent.InputTuple, BaseUrisUpdatedEvent.OutputTuple, BaseUrisUpdatedEvent.OutputObject>;
    

      'BatchMetadataUpdate(uint256,uint256)': TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
      BatchMetadataUpdate: TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
    

      'CheckInRegistryUpdated(address,address)': TypedContractEvent<CheckInRegistryUpdatedEvent.InputTuple, CheckInRegistryUpdatedEvent.OutputTuple, CheckInRegistryUpdatedEvent.OutputObject>;
      CheckInRegistryUpdated: TypedContractEvent<CheckInRegistryUpdatedEvent.InputTuple, CheckInRegistryUpdatedEvent.OutputTuple, CheckInRegistryUpdatedEvent.OutputObject>;
    

      'CollectibleModeUpdated(bool)': TypedContractEvent<CollectibleModeUpdatedEvent.InputTuple, CollectibleModeUpdatedEvent.OutputTuple, CollectibleModeUpdatedEvent.OutputObject>;
      CollectibleModeUpdated: TypedContractEvent<CollectibleModeUpdatedEvent.InputTuple, CollectibleModeUpdatedEvent.OutputTuple, CollectibleModeUpdatedEvent.OutputObject>;
    

      'CoverageClaimMarked(uint256,uint64)': TypedContractEvent<CoverageClaimMarkedEvent.InputTuple, CoverageClaimMarkedEvent.OutputTuple, CoverageClaimMarkedEvent.OutputObject>;
      CoverageClaimMarked: TypedContractEvent<CoverageClaimMarkedEvent.InputTuple, CoverageClaimMarkedEvent.OutputTuple, CoverageClaimMarkedEvent.OutputObject>;
    

      'CoveragePurchased(uint256,uint256)': TypedContractEvent<CoveragePurchasedEvent.InputTuple, CoveragePurchasedEvent.OutputTuple, CoveragePurchasedEvent.OutputObject>;
      CoveragePurchased: TypedContractEvent<CoveragePurchasedEvent.InputTuple, CoveragePurchasedEvent.OutputTuple, CoveragePurchasedEvent.OutputObject>;
    

      'EIP712DomainChanged()': TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
      EIP712DomainChanged: TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
    

      'FanPassMinted(address,uint256,bool)': TypedContractEvent<FanPassMintedEvent.InputTuple, FanPassMintedEvent.OutputTuple, FanPassMintedEvent.OutputObject>;
      FanPassMinted: TypedContractEvent<FanPassMintedEvent.InputTuple, FanPassMintedEvent.OutputTuple, FanPassMintedEvent.OutputObject>;
    

      'InsurancePoolUpdated(address,address)': TypedContractEvent<InsurancePoolUpdatedEvent.InputTuple, InsurancePoolUpdatedEvent.OutputTuple, InsurancePoolUpdatedEvent.OutputObject>;
      InsurancePoolUpdated: TypedContractEvent<InsurancePoolUpdatedEvent.InputTuple, InsurancePoolUpdatedEvent.OutputTuple, InsurancePoolUpdatedEvent.OutputObject>;
    

      'MarketplaceUpdated(address,address)': TypedContractEvent<MarketplaceUpdatedEvent.InputTuple, MarketplaceUpdatedEvent.OutputTuple, MarketplaceUpdatedEvent.OutputObject>;
      MarketplaceUpdated: TypedContractEvent<MarketplaceUpdatedEvent.InputTuple, MarketplaceUpdatedEvent.OutputTuple, MarketplaceUpdatedEvent.OutputObject>;
    

      'MetadataUpdate(uint256)': TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
      MetadataUpdate: TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PrimaryMinted(address,uint256,uint256)': TypedContractEvent<PrimaryMintedEvent.InputTuple, PrimaryMintedEvent.OutputTuple, PrimaryMintedEvent.OutputObject>;
      PrimaryMinted: TypedContractEvent<PrimaryMintedEvent.InputTuple, PrimaryMintedEvent.OutputTuple, PrimaryMintedEvent.OutputObject>;
    

      'RewardsUpdated(address,address)': TypedContractEvent<RewardsUpdatedEvent.InputTuple, RewardsUpdatedEvent.OutputTuple, RewardsUpdatedEvent.OutputObject>;
      RewardsUpdated: TypedContractEvent<RewardsUpdatedEvent.InputTuple, RewardsUpdatedEvent.OutputTuple, RewardsUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'StandardMinted(address,uint256,bool)': TypedContractEvent<StandardMintedEvent.InputTuple, StandardMintedEvent.OutputTuple, StandardMintedEvent.OutputObject>;
      StandardMinted: TypedContractEvent<StandardMintedEvent.InputTuple, StandardMintedEvent.OutputTuple, StandardMintedEvent.OutputObject>;
    

      'TicketConsumed(uint256,address,uint8)': TypedContractEvent<TicketConsumedEvent.InputTuple, TicketConsumedEvent.OutputTuple, TicketConsumedEvent.OutputObject>;
      TicketConsumed: TypedContractEvent<TicketConsumedEvent.InputTuple, TicketConsumedEvent.OutputTuple, TicketConsumedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }