/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICollectibleNFTInterface extends Interface {
    getFunction(nameOrSignature: "mintCollectible"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'mintCollectible', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'mintCollectible', data: BytesLike): Result;
  }

  

  export interface ICollectibleNFT extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICollectibleNFT;
    waitForDeployment(): Promise<this>;

    interface: ICollectibleNFTInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    mintCollectible: TypedContractMethod<
      [to: AddressLike, originFan: AddressLike, sourceTicketId: BigNumberish, sourceTicketClass: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'mintCollectible'): TypedContractMethod<
      [to: AddressLike, originFan: AddressLike, sourceTicketId: BigNumberish, sourceTicketClass: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }