/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IFanScoreRegistryInterface extends Interface {
    getFunction(nameOrSignature: "artistAttendanceOf" | "recordAttendance" | "recordBuyback" | "recordMint" | "recordPurchase" | "reputationOf" | "tierOf"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'artistAttendanceOf', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'recordAttendance', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordBuyback', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordMint', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordPurchase', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reputationOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tierOf', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'artistAttendanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordAttendance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordBuyback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordPurchase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tierOf', data: BytesLike): Result;
  }

  

  export interface IFanScoreRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IFanScoreRegistry;
    waitForDeployment(): Promise<this>;

    interface: IFanScoreRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    artistAttendanceOf: TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    recordAttendance: TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordBuyback: TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordMint: TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordPurchase: TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reputationOf: TypedContractMethod<
      [fan: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    tierOf: TypedContractMethod<
      [fan: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'artistAttendanceOf'): TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'recordAttendance'): TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordBuyback'): TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordMint'): TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordPurchase'): TypedContractMethod<
      [fan: AddressLike, artistKey: BytesLike, scoreAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationOf'): TypedContractMethod<
      [fan: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tierOf'): TypedContractMethod<
      [fan: AddressLike, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }