/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IFanFuelBankInterface extends Interface {
    getFunction(nameOrSignature: "balanceOf" | "reward" | "spendFrom"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'reward', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'spendFrom', values: [AddressLike, BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'spendFrom', data: BytesLike): Result;
  }

  

  export interface IFanFuelBank extends BaseContract {
    
    connect(runner?: ContractRunner | null): IFanFuelBank;
    waitForDeployment(): Promise<this>;

    interface: IFanFuelBankInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balanceOf: TypedContractMethod<
      [fan: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    reward: TypedContractMethod<
      [fan: AddressLike, amount: BigNumberish, reason: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    spendFrom: TypedContractMethod<
      [fan: AddressLike, amount: BigNumberish, reason: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [fan: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'reward'): TypedContractMethod<
      [fan: AddressLike, amount: BigNumberish, reason: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'spendFrom'): TypedContractMethod<
      [fan: AddressLike, amount: BigNumberish, reason: BytesLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }