/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IInsurancePoolInterface extends Interface {
    getFunction(nameOrSignature: "currentPolicy" | "registerCoverage"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'currentPolicy', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerCoverage', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'currentPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerCoverage', data: BytesLike): Result;
  }

  

  export interface IInsurancePool extends BaseContract {
    
    connect(runner?: ContractRunner | null): IInsurancePool;
    waitForDeployment(): Promise<this>;

    interface: IInsurancePoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    currentPolicy: TypedContractMethod<
      [],
      [[boolean, bigint, bigint, string] & {active: boolean, payoutBps: bigint, roundId: bigint, reportHash: string }],
      'view'
    >
    

    
    registerCoverage: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'currentPolicy'): TypedContractMethod<
      [],
      [[boolean, bigint, bigint, string] & {active: boolean, payoutBps: bigint, roundId: bigint, reportHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'registerCoverage'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'payable'
    >;

    

    filters: {
      
    };
  }