/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICheckInRegistry } from './ICheckInRegistry.js';
export type { ICollectibleNFT } from './ICollectibleNFT.js';
export type { IERC4494 } from './IERC4494.js';
export type { IFanFuelBank } from './IFanFuelBank.js';
export type { IFanScoreRegistry } from './IFanScoreRegistry.js';
export type { IInsurancePool } from './IInsurancePool.js';
export type { ITicketNFT } from './ITicketNFT.js';
export type { ITicketNFTV2 } from './ITicketNFTV2.js';
export type { ITicketSystemState } from './ITicketSystemState.js';