/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ITicketNFTV2Interface extends Interface {
    getFunction(nameOrSignature: "balanceOf" | "consumeForCheckIn" | "coverageClaimed" | "getApproved" | "isApprovedForAll" | "isUsed" | "markCoverageClaimed" | "maxPerWallet" | "ownerOf" | "paused" | "permit" | "primaryPrice" | "safeTransferFrom" | "ticketClassOf"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'consumeForCheckIn', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'coverageClaimed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isUsed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markCoverageClaimed', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'maxPerWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'permit', values: [AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'primaryPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeTransferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'ticketClassOf', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'consumeForCheckIn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'coverageClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markCoverageClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxPerWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'permit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'primaryPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ticketClassOf', data: BytesLike): Result;
  }

  

  export interface ITicketNFTV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): ITicketNFTV2;
    waitForDeployment(): Promise<this>;

    interface: ITicketNFTV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    consumeForCheckIn: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[string, bigint] & {owner: string, ticketClass: bigint }],
      'nonpayable'
    >
    

    
    coverageClaimed: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isUsed: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    markCoverageClaimed: TypedContractMethod<
      [tokenId: BigNumberish, roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    maxPerWallet: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    permit: TypedContractMethod<
      [spender: AddressLike, tokenId: BigNumberish, deadline: BigNumberish, signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    primaryPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    safeTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    ticketClassOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'consumeForCheckIn'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[string, bigint] & {owner: string, ticketClass: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'coverageClaimed'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isUsed'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'markCoverageClaimed'): TypedContractMethod<
      [tokenId: BigNumberish, roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'maxPerWallet'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'permit'): TypedContractMethod<
      [spender: AddressLike, tokenId: BigNumberish, deadline: BigNumberish, signature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'primaryPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'safeTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ticketClassOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }